[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.deploy]
# This profile is for deployment and verification
via_ir = false
solc_version = "0.8.28" # Pin the version to match default
optimizer = true
optimizer_runs = 200


src = "src"
out = "out"
libs = ["lib"]
extra_output = ["abi"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@solidity-mmr/=lib/herodotus-evm-v2/lib/solidity-mmr/src/',
    'ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    'halmos-cheatcodes/=lib/herodotus-evm-v2/lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/',
    'herodotus-evm-v2/=lib/herodotus-evm-v2/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'solidity-mmr/=lib/herodotus-evm-v2/lib/solidity-mmr/src/'
]
#     "src/contracts/=./src/contracts/",
#     # herodotus helper subâ€‘folder
#     "src/libraries/internal/=lib/herodotus-evm-v2/src/libraries/internal/",
#     # rest of the helpers
#     "src/libraries/=./src/libraries/",
#     "forge-std/=lib/forge-std/src/",
#     "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
#     "ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
#     "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
#     "openzeppelin-contracts/=lib/openzeppelin-contracts/",
#     "src/=lib/herodotus-evm-v2/src/",

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
