[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.deploy]
# This profile is for deployment and verification
via_ir = false
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

# Core settings
src = "src"
out = "out"
libs = ["lib"]

# Minimal, correct remappings
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    '@HerodotusDev/satellite/=lib/satellite/', 
    'permit2/=lib/permit2/'
]